export const MIME_TYPES = {
  IMAGE: {
    JPEG: 'image/jpeg',
    JPG: 'image/jpg',
    PNG: 'image/png',
    GIF: 'image/gif',
    WEBP: 'image/webp',
    SVG: 'image/svg+xml',
  },
  DOCUMENT: {
    PDF: 'application/pdf',
    DOC: 'application/msword',
    DOCX: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    XLS: 'application/vnd.ms-excel',
    XLSX: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    PPT: 'application/vnd.ms-powerpoint',
    PPTX: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    TXT: 'text/plain',
  },
  VIDEO: {
    MP4: 'video/mp4',
    MPEG: 'video/mpeg',
    MOV: 'video/quicktime',
    AVI: 'video/x-msvideo',
    WEBM: 'video/webm',
  },
  AUDIO: {
    MP3: 'audio/mpeg',
    WAV: 'audio/wav',
    OGG: 'audio/ogg',
    M4A: 'audio/mp4',
    WEBM_AUDIO: 'audio/webm',
  },
  SPREADSHEET: {
    XLS: 'application/vnd.ms-excel',
    XLSX: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    CSV: 'text/csv',
  },
  ARCHIVE: {
    ZIP: 'application/zip',
    RAR: 'application/x-rar-compressed',
    SEVEN_ZIP: 'application/x-7z-compressed',
    GZIP: 'application/gzip',
  },
} as const;

export const FILE_EXTENSIONS = {
  IMAGE: {
    JPG: '.jpg',
    JPEG: '.jpeg',
    PNG: '.png',
    GIF: '.gif',
    WEBP: '.webp',
    SVG: '.svg',
  },
  DOCUMENT: {
    PDF: '.pdf',
    DOC: '.doc',
    DOCX: '.docx',
    XLS: '.xls',
    XLSX: '.xlsx',
    PPT: '.ppt',
    PPTX: '.pptx',
    TXT: '.txt',
  },
  VIDEO: {
    MP4: '.mp4',
    MPEG: '.mpeg',
    MOV: '.mov',
    AVI: '.avi',
    WEBM: '.webm',
  },
  AUDIO: {
    MP3: '.mp3',
    WAV: '.wav',
    OGG: '.ogg',
    M4A: '.m4a',
    WEBM: '.webm',
  },
  SPREADSHEET: {
    XLS: '.xls',
    XLSX: '.xlsx',
    CSV: '.csv',
  },
  ARCHIVE: {
    ZIP: '.zip',
    RAR: '.rar',
    SEVEN_ZIP: '.7z',
    GZIP: '.gz',
  },
} as const;
